### ISSUE TITLE
PythonScalarFunction is not serializable

### ISSUE THREAD

**Issue by afedulov** [dianfu/pyflink-faq#3]
@dianfu thanks for sharing this repo, I believe it is exactly what I was looking for. Unfortunately I face an issue when following  the instructions and running  `python3 -m unittest test_table_api.TableTests.test_scalar_function`. Do you know what the issue could be?

```
Using %s as FLINK_HOME... /Users/afedulov/dev/pyflink-faq/testing/.venv/lib/python3.9/site-packages/pyflink
Skipped download /Users/afedulov/dev/pyflink-faq/testing/flink-python-1.16.1-tests.jar since it already exists.
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py:1052: ResourceWarning: subprocess 70753 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
E
======================================================================
ERROR: test_scalar_function (test_table_api.TableTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/afedulov/dev/pyflink-faq/testing/test_table_api.py", line 46, in test_scalar_function
    t.select(t.a, add_one(t.a)) \
  File "/Users/afedulov/dev/pyflink-faq/testing/.venv/lib/python3.9/site-packages/pyflink/table/table.py", line 131, in select
    return Table(self._j_table.select(to_expression_jarray(fields)), self._t_env)
  File "/Users/afedulov/dev/pyflink-faq/testing/.venv/lib/python3.9/site-packages/py4j/java_gateway.py", line 1321, in __call__
    return_value = get_return_value(
  File "/Users/afedulov/dev/pyflink-faq/testing/.venv/lib/python3.9/site-packages/pyflink/util/exceptions.py", line 146, in deco
    return f(*a, **kw)
  File "/Users/afedulov/dev/pyflink-faq/testing/.venv/lib/python3.9/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o45.select.
: org.apache.flink.table.api.ValidationException: Function class 'class org.apache.flink.table.functions.python.PythonScalarFunction' is not serializable. Make sure that the class is self-contained (i.e. no references to outer classes) and all inner fields are serializable as well.
	at org.apache.flink.table.functions.UserDefinedFunctionHelper.cleanFunction(UserDefinedFunctionHelper.java:553)
	at org.apache.flink.table.functions.UserDefinedFunctionHelper.prepareInstance(UserDefinedFunctionHelper.java:253)
	at org.apache.flink.table.expressions.resolver.rules.ResolveCallByArgumentsRule$ResolvingCallVisitor.prepareInlineUserDefinedFunction(ResolveCallByArgumentsRule.java:349)
	at org.apache.flink.table.expressions.resolver.rules.ResolveCallByArgumentsRule$ResolvingCallVisitor.visit(ResolveCallByArgumentsRule.java:114)
	at org.apache.flink.table.expressions.resolver.rules.ResolveCallByArgumentsRule$ResolvingCallVisitor.visit(ResolveCallByArgumentsRule.java:98)
	at org.apache.flink.table.expressions.ApiExpressionVisitor.visit(ApiExpressionVisitor.java:37)
	at org.apache.flink.table.expressions.UnresolvedCallExpression.accept(UnresolvedCallExpression.java:97)
	at org.apache.flink.table.expressions.resolver.rules.ResolveCallByArgumentsRule.lambda$apply$0(ResolveCallByArgumentsRule.java:92)
	...
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @29290c6
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	...
	... 32 more


----------------------------------------------------------------------
Ran 1 test in 1.526s

FAILED (errors=1)
sys:1: ResourceWarning: unclosed file <_io.BufferedWriter name=5>
```

**Comment by afedulov** [comment]
The issue was caused by using Java 17.

**Comment by dianfu** [comment]
@afedulov Oh, sorry for late response.

In JDK17, we should add the following JVM options when starting up the JVM, e.g. "-XX:+IgnoreUnrecognizedVMOptions --add-opens=jdk.proxy2/jdk.proxy2=ALL-UNNAMED". This is already supported in PyFlink since 1.18.0. See https://github.com/apache/flink/blob/master/flink-python/pyflink/pyflink_gateway_server.py#L257 for more details.

If you are using versions below 1.18.0, I guess you could set environment variable JVM_ARGS to "-XX:+IgnoreUnrecognizedVMOptions --add-opens=jdk.proxy2/jdk.proxy2=ALL-UNNAMED" to work around this issue.

**Comment by afedulov** [comment]
@dianfu Thanks!
